# Site settings
title: Louis Absil
email: louis.absil@gmail.com
description: "Pianiste, accompagnateur, organiste"
baseurl: ""
url: "http://louis.absil.fr"
paginate: 10
paginate_path: "/page:num/"

collections:
 files:
   output: true

# Build settings
markdown: kramdown
permalink: pretty

sass:
    style: compressed
